---

- hosts: all
  
  tasks:
   - apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present
   - apt_repository: repo='deb http://download.ceph.com/debian-jewel/ trusty main' state=present update_cache='yes'
   - apt: name='ceph-deploy' state='present' update_cache='yes'
   - name: Creates directory
     file: path=/root/my-cluster
   - name: ceph-deploy new monitor
     shell: ceph-deploy new client2.skyfall chdir=/root/my-cluster